name: application
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.5
  google_maps_flutter: ^2.3.1
  url_launcher: ^6.1.12
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2
  get: ^4.6.5
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  firebase_messaging: ^14.6.6
  flutter_localizations:
        sdk: flutter
  firebase_storage: ^11.2.6
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path: 'images/logo.png'
  adaptive_icon_backgraound: '#ffffff'

flutter:
  uses-material-design: true

  fonts:
    - family: cairo
      fonts:
        - asset: fonts/Cairo-VariableFont_slnt,wght.ttf

  assets:
    - images/logo.png
    - images/cover.png
    - images/splash.png
flutter_intl:
  enabled: true
