name: application
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.5
  google_maps_flutter: ^2.3.1
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  fonts:
    - family: cairo
      fonts:
        - asset: fonts/Cairo-VariableFont_slnt,wght.ttf

  assets:
    - images/logo2.png  
